services:
  postgres:
    image: postgres:16-alpine
    container_name: wandermap-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wandermap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: wandermap-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: always

volumes:
  pgdata:
  redisdata:
